# Start base image
FROM node:16-alpine

WORKDIR '/app'

# Copy package.json to the container
COPY package.json .

# Install dependencies
RUN npm install

# Copy the rest of the files to the container
COPY . .

# Start the app
CMD ["npm", "run", "start"]
